name: Fadah
version: '${version}'
main: info.preva1l.fadah.Fadah
api-version: '1.19'
depend: [Vault]
authors: [Preva1l]
description: Fadah (Finally a Decent Auction House) is the fast, modern and advanced auction house plugin that you have been looking for!
website: https://discord.gg/4KcF7S94HF
libraries:
  - redis.clients:jedis:5.1.0
  - org.apache.commons:commons-pool2:2.12.0
  - com.mysql:mysql-connector-j:8.3.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3